#version 460 core

layout(local_size_x=1) in;

#define GLOBAL_PARAMETERS_BINDING       0
#define NEXT_GLOBAL_PARAMETERS_BINDING  1
#include "../common.glsli"
#include "../bindings.glsli"

void main()
{
    nextGlobals[GLOBAL_OFFSET_PIPELINESTAGE] = PIPELINE_STAGE_LOADMAP;
    nextGlobals[GLOBAL_OFFSET_LEVELGENSEED] = simpleHash32(uvec3(globals.cpuRandom, globals.cpuTime, globals.levelGenSeed));
    nextGlobals[GLOBAL_OFFSET_CURRENTLEVEL] = 0u;
}
