#ifndef ATLAS_ASSET_AUTOGEN_GLSL
#define ATLAS_ASSET_AUTOGEN_GLSL

// Auto generated file, do not edit by hand.
// use tiles_to_atlas.py to regenerate it.

#define ASSET_ATLAS_WIDTH  192
#define ASSET_ATLAS_HEIGHT 192
#define ASSET_ATLAS_NUM    146

#define ASSET_ATLAS_ID_BLOOD_DECL_V0    0
#define ASSET_ATLAS_ID_BLOOD_DECL_V1    1
#define ASSET_ATLAS_ID_BLOOD_DECL_V2    2
#define ASSET_ATLAS_ID_BLOOD_DECL_V3    3
#define ASSET_ATLAS_ID_BRICKS_L00_V0    4
#define ASSET_ATLAS_ID_BRICKS_L00_V1    5
#define ASSET_ATLAS_ID_BRICKS_L00_V2    6
#define ASSET_ATLAS_ID_BRICKS_L00_V3    7
#define ASSET_ATLAS_ID_BRICKS_L00_V4    8
#define ASSET_ATLAS_ID_BRICKS_L00_V5    9
#define ASSET_ATLAS_ID_BRICKS_L00_V6    10
#define ASSET_ATLAS_ID_BRICKS_L00_V7    11
#define ASSET_ATLAS_ID_BRICKS_L01_V0    12
#define ASSET_ATLAS_ID_BRICKS_L01_V1    13
#define ASSET_ATLAS_ID_BRICKS_L01_V2    14
#define ASSET_ATLAS_ID_BRICKS_L01_V3    15
#define ASSET_ATLAS_ID_BRICKS_L01_V4    16
#define ASSET_ATLAS_ID_BRICKS_L01_V5    17
#define ASSET_ATLAS_ID_BRICKS_L01_V6    18
#define ASSET_ATLAS_ID_BRICKS_L01_V7    19
#define ASSET_ATLAS_ID_BRICKS_L02_V0    20
#define ASSET_ATLAS_ID_BRICKS_L02_V1    21
#define ASSET_ATLAS_ID_BRICKS_L02_V2    22
#define ASSET_ATLAS_ID_BRICKS_L02_V3    23
#define ASSET_ATLAS_ID_BRICKS_L02_V4    24
#define ASSET_ATLAS_ID_BRICKS_L02_V5    25
#define ASSET_ATLAS_ID_BRICKS_L02_V6    26
#define ASSET_ATLAS_ID_BRICKS_L02_V7    27
#define ASSET_ATLAS_ID_BRICKS_L03_V0    28
#define ASSET_ATLAS_ID_BRICKS_L03_V1    29
#define ASSET_ATLAS_ID_BRICKS_L03_V2    30
#define ASSET_ATLAS_ID_BRICKS_L03_V3    31
#define ASSET_ATLAS_ID_BRICKS_L03_V4    32
#define ASSET_ATLAS_ID_BRICKS_L03_V5    33
#define ASSET_ATLAS_ID_BRICKS_L03_V6    34
#define ASSET_ATLAS_ID_BRICKS_L03_V7    35
#define ASSET_ATLAS_ID_BRICKS_L04_V0    36
#define ASSET_ATLAS_ID_BRICKS_L04_V1    37
#define ASSET_ATLAS_ID_BRICKS_L04_V2    38
#define ASSET_ATLAS_ID_BRICKS_L04_V3    39
#define ASSET_ATLAS_ID_BRICKS_L04_V4    40
#define ASSET_ATLAS_ID_BRICKS_L04_V5    41
#define ASSET_ATLAS_ID_BRICKS_L04_V6    42
#define ASSET_ATLAS_ID_BRICKS_L04_V7    43
#define ASSET_ATLAS_ID_BRICKS_L05_V0    44
#define ASSET_ATLAS_ID_BRICKS_L05_V1    45
#define ASSET_ATLAS_ID_BRICKS_L05_V2    46
#define ASSET_ATLAS_ID_BRICKS_L05_V3    47
#define ASSET_ATLAS_ID_BRICKS_L05_V4    48
#define ASSET_ATLAS_ID_BRICKS_L05_V5    49
#define ASSET_ATLAS_ID_BRICKS_L05_V6    50
#define ASSET_ATLAS_ID_BRICKS_L05_V7    51
#define ASSET_ATLAS_ID_BRICKS_L06_V0    52
#define ASSET_ATLAS_ID_BRICKS_L06_V1    53
#define ASSET_ATLAS_ID_BRICKS_L06_V2    54
#define ASSET_ATLAS_ID_BRICKS_L06_V3    55
#define ASSET_ATLAS_ID_BRICKS_L06_V4    56
#define ASSET_ATLAS_ID_BRICKS_L06_V5    57
#define ASSET_ATLAS_ID_BRICKS_L06_V6    58
#define ASSET_ATLAS_ID_BRICKS_L06_V7    59
#define ASSET_ATLAS_ID_BRICKS_L07_V0    60
#define ASSET_ATLAS_ID_BRICKS_L07_V1    61
#define ASSET_ATLAS_ID_BRICKS_L07_V2    62
#define ASSET_ATLAS_ID_BRICKS_L07_V3    63
#define ASSET_ATLAS_ID_BRICKS_L07_V4    64
#define ASSET_ATLAS_ID_BRICKS_L07_V5    65
#define ASSET_ATLAS_ID_BRICKS_L07_V6    66
#define ASSET_ATLAS_ID_BRICKS_L07_V7    67
#define ASSET_ATLAS_ID_CHAR0_IDLE_BCK   68
#define ASSET_ATLAS_ID_CHAR0_IDLE_FWD   69
#define ASSET_ATLAS_ID_CHAR0_IDLE_RGT   70
#define ASSET_ATLAS_ID_CHAR0_WALK_BCK0  71
#define ASSET_ATLAS_ID_CHAR0_WALK_BCK1  72
#define ASSET_ATLAS_ID_CHAR0_WALK_BCK2  73
#define ASSET_ATLAS_ID_CHAR0_WALK_BCK3  74
#define ASSET_ATLAS_ID_CHAR0_WALK_FWD0  75
#define ASSET_ATLAS_ID_CHAR0_WALK_FWD1  76
#define ASSET_ATLAS_ID_CHAR0_WALK_FWD2  77
#define ASSET_ATLAS_ID_CHAR0_WALK_FWD3  78
#define ASSET_ATLAS_ID_CHAR0_WALK_RGT0  79
#define ASSET_ATLAS_ID_CHAR0_WALK_RGT1  80
#define ASSET_ATLAS_ID_EMPTY            81
#define ASSET_ATLAS_ID_GROUND_L00_V0    82
#define ASSET_ATLAS_ID_GROUND_L00_V1    83
#define ASSET_ATLAS_ID_GROUND_L00_V2    84
#define ASSET_ATLAS_ID_GROUND_L00_V3    85
#define ASSET_ATLAS_ID_GROUND_L00_V4    86
#define ASSET_ATLAS_ID_GROUND_L00_V5    87
#define ASSET_ATLAS_ID_GROUND_L00_V6    88
#define ASSET_ATLAS_ID_GROUND_L00_V7    89
#define ASSET_ATLAS_ID_GROUND_L01_V0    90
#define ASSET_ATLAS_ID_GROUND_L01_V1    91
#define ASSET_ATLAS_ID_GROUND_L01_V2    92
#define ASSET_ATLAS_ID_GROUND_L01_V3    93
#define ASSET_ATLAS_ID_GROUND_L01_V4    94
#define ASSET_ATLAS_ID_GROUND_L01_V5    95
#define ASSET_ATLAS_ID_GROUND_L01_V6    96
#define ASSET_ATLAS_ID_GROUND_L01_V7    97
#define ASSET_ATLAS_ID_GROUND_L02_V0    98
#define ASSET_ATLAS_ID_GROUND_L02_V1    99
#define ASSET_ATLAS_ID_GROUND_L02_V2    100
#define ASSET_ATLAS_ID_GROUND_L02_V3    101
#define ASSET_ATLAS_ID_GROUND_L02_V4    102
#define ASSET_ATLAS_ID_GROUND_L02_V5    103
#define ASSET_ATLAS_ID_GROUND_L02_V6    104
#define ASSET_ATLAS_ID_GROUND_L02_V7    105
#define ASSET_ATLAS_ID_GROUND_L03_V0    106
#define ASSET_ATLAS_ID_GROUND_L03_V1    107
#define ASSET_ATLAS_ID_GROUND_L03_V2    108
#define ASSET_ATLAS_ID_GROUND_L03_V3    109
#define ASSET_ATLAS_ID_GROUND_L03_V4    110
#define ASSET_ATLAS_ID_GROUND_L03_V5    111
#define ASSET_ATLAS_ID_GROUND_L03_V6    112
#define ASSET_ATLAS_ID_GROUND_L03_V7    113
#define ASSET_ATLAS_ID_GROUND_L04_V0    114
#define ASSET_ATLAS_ID_GROUND_L04_V1    115
#define ASSET_ATLAS_ID_GROUND_L04_V2    116
#define ASSET_ATLAS_ID_GROUND_L04_V3    117
#define ASSET_ATLAS_ID_GROUND_L04_V4    118
#define ASSET_ATLAS_ID_GROUND_L04_V5    119
#define ASSET_ATLAS_ID_GROUND_L04_V6    120
#define ASSET_ATLAS_ID_GROUND_L04_V7    121
#define ASSET_ATLAS_ID_GROUND_L05_V0    122
#define ASSET_ATLAS_ID_GROUND_L05_V1    123
#define ASSET_ATLAS_ID_GROUND_L05_V2    124
#define ASSET_ATLAS_ID_GROUND_L05_V3    125
#define ASSET_ATLAS_ID_GROUND_L05_V4    126
#define ASSET_ATLAS_ID_GROUND_L05_V5    127
#define ASSET_ATLAS_ID_GROUND_L05_V6    128
#define ASSET_ATLAS_ID_GROUND_L05_V7    129
#define ASSET_ATLAS_ID_GROUND_L06_V0    130
#define ASSET_ATLAS_ID_GROUND_L06_V1    131
#define ASSET_ATLAS_ID_GROUND_L06_V2    132
#define ASSET_ATLAS_ID_GROUND_L06_V3    133
#define ASSET_ATLAS_ID_GROUND_L06_V4    134
#define ASSET_ATLAS_ID_GROUND_L06_V5    135
#define ASSET_ATLAS_ID_GROUND_L06_V6    136
#define ASSET_ATLAS_ID_GROUND_L06_V7    137
#define ASSET_ATLAS_ID_GROUND_L07_V0    138
#define ASSET_ATLAS_ID_GROUND_L07_V1    139
#define ASSET_ATLAS_ID_GROUND_L07_V2    140
#define ASSET_ATLAS_ID_GROUND_L07_V3    141
#define ASSET_ATLAS_ID_GROUND_L07_V4    142
#define ASSET_ATLAS_ID_GROUND_L07_V5    143
#define ASSET_ATLAS_ID_GROUND_L07_V6    144
#define ASSET_ATLAS_ID_GROUND_L07_V7    145


struct AssetAtlasInfo
{
    uvec4 atlasPixelRegion;
    uvec2 size;
    uvec4 rectPadding;
    uvec4 roi;
    vec4  atlasUvRegion;
};


AssetAtlasInfo unpackAssetAtlasInfo(uvec4 packedData)
{
    AssetAtlasInfo result;

    result.atlasPixelRegion.x = packedData.x & 0xffffu;
    result.atlasPixelRegion.y = packedData.x >> 16;
    result.atlasPixelRegion.z = packedData.y & 0xffffu;
    result.atlasPixelRegion.w = packedData.y >> 16;
    result.size.x = packedData.z & 0xffffu;
    result.size.y = packedData.z >> 16;
    result.rectPadding.x = packedData.w & 0xffu;
    result.rectPadding.y = (packedData.w >> 8) & 0xffu;
    result.rectPadding.z = (packedData.w >> 16) & 0xffu;
    result.rectPadding.w = (packedData.w >> 24);

    result.roi.xy = result.rectPadding.xy;
    result.roi.zw = result.size - result.rectPadding.zw;

    result.atlasUvRegion = vec4(result.atlasPixelRegion) 
                           / vec2(ASSET_ATLAS_WIDTH, ASSET_ATLAS_HEIGHT).xyxy;

    return result;
}


// glslc doesn't allow passing buffers as arguments.
#define loadAssetAtlasInfo(atlasIndex, buf) \
                   unpackAssetAtlasInfo(buf[atlasIndex])


#endif // ATLAS_ASSET_AUTOGEN_GLSL
